apiVersion: apps/v1
kind: Deployment
metadata:
    name: webapp
    namespace: backend
    labels:
        app: webapp
spec:
    replicas: 3
    selector:
        matchLabels:
            app: webapp
    template:
        metadata:
            labels:
                app: webapp
        spec:
            containers:
              - name: webapp
                image: cezaryszukiel/ckad:podman
                ports:
                  - containerPort: 8080
                resources:
                  limits:
                    memory: "128Mi"
                    cpu: "200m"
